name: spotmies
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase: ^9.0.3
  firebase_core: ^1.17.1
  firebase_auth: ^3.3.19
  cloud_firestore: ^3.1.17
  image_picker: ^0.8.5+3
  pinput: ^2.2.11
  # share: ^2.0.1
  # geocoder: ^0.2.1
  geolocator: ^9.0.0
  firebase_storage: ^10.2.17
  # flutter_spinkit: ^5.0.0
  flutter_icons: ^1.1.0
  http: ^0.13.4
  step_progress_indicator: ^1.0.2
  simple_animations: ^4.2.0
  google_fonts: ^2.2.0
  intl: ^0.17.0
  flutter_local_notifications: ^9.6.1
  provider: ^6.0.3
  google_maps_flutter: ^2.1.8
  material_floating_search_bar: ^0.3.7
  percent_indicator: ^4.2.2
  animated_bottom_navigation_bar: ^0.3.3
  mvc_pattern: ^8.10.2
  carousel_slider: ^4.1.1
  url_launcher: ^6.1.3
  webview_flutter: ^3.0.4
  flutter_typeahead: ^4.0.0
  fluttertoast: ^8.0.9
  shimmer: ^2.0.0
  shared_preferences: ^2.0.15
  socket_io_client: ^1.0.2
  flutter_svg:
  dotted_border:
  video_player: any
  flutter_webrtc: any
  lottie: any
  photo_view: any
  permission_handler: any
  # flutter_audio_recorder2: any
  audioplayers: any
  path_provider: any
  timelines: any
  firebase_messaging: any
  rxdart: any
  flutter_native_timezone: any
  awesome_notifications: ^0.6.21
  country_code_picker: any
  geocoding: ^2.0.4
  scrollable_positioned_list: ^0.3.2
  syncfusion_flutter_gauges: ^20.2.36
  flutter_staggered_grid_view: ^0.6.1
  # flutter_incall: any

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  get: ^4.6.5
  easy_localization: ^3.0.1

dev_dependencies:
  # flutter_lints: ^1.0.4
  # flutter_launcher_icons: "^0.9.2"
  flutter_test:
    sdk: flutter
# flutter_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "assets/icons/app_icon.png"
#   remove_alpha_ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # - assets/1.png
    # - assets/2.png
    # - assets/3.png
    # - assets/4.png
    # - assets/5.png
    # - assets/6.svg
    # - assets/images/
    # - assets/icons/
    # - assets/intro.svg
    # - assets/introBook.svg
    # - assets/share.svg
    # - assets/promo.svg
    # - assets/exit.svg
    # - assets/settings.svg
    # - assets/edit.svg
    # - assets/like.svg
    # - assets/help.svg
    # - assets/history.svg
    # - assets/getQuotes.svg
    # - assets/getService.svg
    # - assets/setLocation.svg
    # - assets/uploadPic.svg
    # - assets/fliming.svg
    # - assets/barber.svg
    # - assets/design.svg
    # - assets/domestic.svg
    # - assets/education.svg
    # - assets/software.svg
    # - assets/tradesman.svg
    # - assets/success.svg
    # - assets/spotmies_logo.json
    # - assets/onPending.json
    # - assets/sending.json
    # - assets/succuss.json
    # - assets/fail.json
    # - assets/login.svg
    # - assets/logo.png
    # - assets/waiting.json
    - assets/translations/
    - assets/catImages/
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: jose
  #     fonts:
  #       - asset: fonts/JosefinSans-VariableFont_wght.ttf
  #         weight: 400
  # - family: Trajan Pro
  #   fonts:
  #     - asset: fonts/TrajanPro.ttf
  #     - asset: fonts/TrajanPro_Bold.ttf
  #       weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
